// Minimal, dependency-free Markdown -> HTML renderer.
//
// It supports exactly the subset used by content/articles/*.md:
//   - "## " headings
//   - paragraphs
//   - **bold** and *italic*
//   - [text](url) links
//   - "- " unordered lists and "1." ordered lists
//   - "> " blockquotes (single and multi-line)
//   - GitHub-style pipe tables
//   - inline raw HTML <a> tags (affiliate links) — passed through verbatim
//     so that rel="nofollow sponsored" is preserved.
//
// Article content is repo-controlled (generated by scripts/generate-article.js
// and curated in-repo), so it is trusted and rendered via
// dangerouslySetInnerHTML.

function inline(text: string): string {
  return text
    // Markdown links [text](url). Raw <a> tags don't match this pattern and
    // are therefore left untouched (preserving their rel attribute).
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    // Bold (processed before italic so ** is consumed first).
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    // Italic (remaining single * pairs).
    .replace(/\*([^*\n]+)\*/g, '<em>$1</em>');
}

function splitRow(line: string): string[] {
  let s = line.trim();
  if (s.startsWith('|')) s = s.slice(1);
  if (s.endsWith('|')) s = s.slice(0, -1);
  return s.split('|').map((c) => c.trim());
}

const isTableSeparator = (s: string) =>
  s.includes('-') && /^\s*\|?[\s:|-]+\|?\s*$/.test(s);

export function renderMarkdown(md: string): string {
  if (!md) return '';

  const lines = md.replace(/\r\n/g, '\n').split('\n');
  const out: string[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    // Blank line.
    if (line.trim() === '') {
      i++;
      continue;
    }

    // Heading (## ... up to ######).
    const heading = line.match(/^(#{1,6})\s+(.*)$/);
    if (heading) {
      const level = heading[1].length;
      out.push(`<h${level}>${inline(heading[2].trim())}</h${level}>`);
      i++;
      continue;
    }

    // Table: a "|" row immediately followed by a separator row.
    if (
      line.trim().startsWith('|') &&
      i + 1 < lines.length &&
      isTableSeparator(lines[i + 1])
    ) {
      const header = splitRow(line);
      i += 2; // skip header + separator
      const rows: string[][] = [];
      while (i < lines.length && lines[i].trim().startsWith('|')) {
        rows.push(splitRow(lines[i]));
        i++;
      }
      let table = '<table class="stats-table"><thead><tr>';
      table += header.map((c) => `<th>${inline(c)}</th>`).join('');
      table += '</tr></thead><tbody>';
      for (const row of rows) {
        table += '<tr>' + row.map((c) => `<td>${inline(c)}</td>`).join('') + '</tr>';
      }
      table += '</tbody></table>';
      out.push(`<div class="stats-table-wrapper">${table}</div>`);
      continue;
    }

    // Blockquote (consecutive "> " lines).
    if (line.trim().startsWith('>')) {
      const buf: string[] = [];
      while (i < lines.length && lines[i].trim().startsWith('>')) {
        buf.push(lines[i].replace(/^\s*>\s?/, ''));
        i++;
      }
      out.push(`<blockquote>${buf.map(inline).join('<br />')}</blockquote>`);
      continue;
    }

    // Unordered list ("- ").
    if (/^\s*-\s+/.test(line)) {
      const items: string[] = [];
      while (i < lines.length && /^\s*-\s+/.test(lines[i])) {
        items.push(lines[i].replace(/^\s*-\s+/, ''));
        i++;
      }
      out.push('<ul>' + items.map((it) => `<li>${inline(it)}</li>`).join('') + '</ul>');
      continue;
    }

    // Ordered list ("1. ").
    if (/^\s*\d+\.\s+/.test(line)) {
      const items: string[] = [];
      while (i < lines.length && /^\s*\d+\.\s+/.test(lines[i])) {
        items.push(lines[i].replace(/^\s*\d+\.\s+/, ''));
        i++;
      }
      out.push('<ol>' + items.map((it) => `<li>${inline(it)}</li>`).join('') + '</ol>');
      continue;
    }

    // Paragraph (gather until a blank line or the start of another block).
    const para: string[] = [];
    while (
      i < lines.length &&
      lines[i].trim() !== '' &&
      !/^#{1,6}\s+/.test(lines[i]) &&
      !lines[i].trim().startsWith('>') &&
      !/^\s*-\s+/.test(lines[i]) &&
      !/^\s*\d+\.\s+/.test(lines[i]) &&
      !lines[i].trim().startsWith('|')
    ) {
      para.push(lines[i].trim());
      i++;
    }
    if (para.length) {
      out.push(`<p>${inline(para.join(' '))}</p>`);
    }
  }

  return out.join('\n');
}
